# Generated by Django 3.1.5 on 2024-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240306_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='null', upload_to='photo/profile/%Y/%m/%d/'),
        ),
    ]
